[package]
name = "tf-rs"
version = "0.1.0"
authors = ["Ignacio Duart <iduart@gmail.com>"]

[dependencies]
tensorflow = { version = "0.6.0", git = "https://github.com/tensorflow/rust" }
uuid = { version = "0.4", features = ["v4"] }
